---
# Include Amazon Linxu 1 tasks
- include: redis-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include AMazon Linux 2 tasks
- include: redis-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
