---
# tasks file for datashades.redis
#

# Because Amazon Linux 2 provides no higher than Redis 4.x we use an RPM from Remi for EL7 
#
- name: Install Redis 6.x RPM from Remi
  yum:
    name: https://datashades-files.s3-ap-southeast-2.amazonaws.com/redis-6.0.9-2.el7.remi.x86_64.rpm
    state: present

- name: Enable Redis to listen for remote connections
  lineinfile:
    path: /etc/redis.conf
    regexp: '^bind 127.0.0.1'
    line: "#bind"
    backrefs: yes
  notify: restart redis
  tags: redis_config

- name: Disable protected mode 
  lineinfile:
    path: /etc/redis.conf
    regexp: '^protected-mode yes'
    line: "protected-mode no"
    backrefs: yes
  notify: restart redis
  tags: redis_config

- name: Enable daemonized mode
  lineinfile:
    path: /etc/redis.conf
    regexp: '^daemonize no'
    line: "daemonize yes"
    backrefs: yes
  notify: restart redis
  tags: redis_config

- name: Set supervised mode to systemd
  lineinfile:
    path: /etc/redis.conf
    regexp: '^supervised no'
    line: "supervised systemd"
    backrefs: yes
  notify: restart redis
  tags: redis_config

- name: Enable Redis on boot
  systemd:
    name: redis
    enabled: yes

- name: Restart Redis
  systemd: 
    name: redis
    state: restarted
