---
# tasks file for datashades.apache

# Include Amazon Linux 1 tasks
- include: apache_al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include Amazon Linux 2 tasks
- include: apache_al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
