---
- hosts: provision-webmaster
  vars:
    host_type: 'web'
    drupal: 'yes'
    drupal_version: '9.3.x' # Drupal version to be installed (i.e. branches of https://github.com/drupal/recommended-project)
  remote_user: ec2-user
  become_user: root
  become: yes
  become_flags: -i
  vars_prompt:
    - name: "email"
      prompt: "Enter your email address for use when creating system accounts:"
      default: ""
      private: no
  pre_tasks:
    - name: Create custom facts directory
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
      tags:
        - always

    - name: Copy environment fact file
      copy:
        src: environment.fact
        dest: /etc/ansible/facts.d/environment.fact
        mode: 0755
      tags:
        - always

    - name: Copy the network fact file
      copy:
        src: network.fact
        dest: /etc/ansible/facts.d/network.fact
        mode: 0755
      tags:
        - always

    - name: Copy the DNS fact file
      copy:
        src: dns.fact
        dest: /etc/ansible/facts.d/dns.fact
        mode: 0755
      tags:
        - always

    - name: Install JQ which is required for the fact scripts
      yum:
        name: jq
        state: latest
      tags:
        - always

    - name: Re-run setup to gather custom facts for playbook run
      setup: filter=ansible_local
      tags:
        - always

  roles:
    - datashades.common
    - datashades.supervisor
    - datashades.webmaster-admin
    - datashades.nginx
    - datashades.php
    - datashades.pyenv
    - datashades.ckan
    - datashades.xloader
    - datashades.drupal9
