---
# tasks file for datashades.datapusher

- name: Create virtualenv for Datapusher and install Datapusher
  command: virtualenv /usr/lib/ckan/datapusher
  args:
    creates: /usr/lib/ckan/datapusher

- name: Create src directory for Datapusher
  file:
    path: /usr/lib/ckan/datapusher/src
    state: directory

- name: Clone Datapusher source from Git
  git:
    repo: https://github.com/ckan/datapusher.git
    clone: yes
    dest: /usr/lib/ckan/datapusher/src/datapusher
    version: 0.0.14

- name: Install Datapusher requirements
  pip:
    requirements: /usr/lib/ckan/datapusher/src/datapusher/requirements.txt
    virtualenv: /usr/lib/ckan/datapusher

- name: Execute python setup
  command: /usr/lib/ckan/datapusher/bin/python setup.py develop 
  args:
    creates: /usr/lib/ckan/datapusher/src/datapusher/datapusher.egg-info
    chdir: /usr/lib/ckan/datapusher/src/datapusher

- name: Set ownership of Datapusher's files to CKAN user
  file:
    path: /usr/lib/ckan/datapusher
    owner: ckan
    group: ckan
    recurse: yes

- name: Copy Apache configuration file.
  template:
    src: datapusher_2.4.conf
    dest: /etc/httpd/conf.d/datapusher.conf
    owner: apache
    group: apache
  notify: restart httpd

- name: Create /etc/ckan/ directory
  file:
    path: /etc/ckan
    state: directory
    mode: 0755

- name: Copy the Datapusher WSGI file.
  copy:
    src: datapusher.wsgi
    dest: /etc/ckan/datapusher.wsgi
  notify: restart httpd

- name: Copy the Datapusher settings file.
  copy:
    src: datapusher_settings.py
    dest: /etc/ckan/datapusher_settings.py
  notify: restart httpd
