---
# tasks file for datashades.datapusher

- include: datapusher-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

- include: datapusher-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
