---
# tasks file for datashades.services-admin-scripts

- include: services_admin-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

- include: services_admin-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
