---
# tasks file for datashades.supervisor

- include: supervisor-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

- include: supervisor-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
