---
# tasks file for datashades.supervisor

- name: Install Supervisor via pip
  pip:
    name: supervisor

- name: Copy Supervisor init script
  copy:
    src: supervisor.init
    dest: /etc/init.d/supervisor
    mode: 0755

- name: Create supervisor.d directory
  file:
    path: /etc/supervisor.d
    state: directory

- name: Create Supervisor config file
  copy:
    src: supervisord.conf
    dest: /etc/supervisord.conf
  notify: restart supervisor

- name: Fix default init script PREFIX path
  lineinfile:
    path: /etc/rc.d/init.d/supervisor
    regexp: '^PREFIX='
    line: 'PREFIX=/usr'

- name: Enable Supervisor on boot
  systemd:
    name: supervisor
    enabled: yes
