---
# tasks file for datashades.supervisor

- name: Install Supervisor
  yum:
    name: supervisor

- name: Modify Supervisor config
  ini_file:
    path: /etc/supervisord.conf
    section: include
    option: files
    value: "supervisord.d/*.conf"

- name: Enable Supervisor on boot
  systemd:
    name: supervisord
    enabled: yes
