---
# tasks file for datashades.postgres

- name: Install PostgreSQL from Amazon Linux Extras
  shell: amazon-linux-extras install postgresql11 -y
  environment:
    PYTHON: "python2"

- name: Install the PostgreSQL server and related packages
  yum:
    name: 
      - postgresql-server
      - postgresql-devel
      - python-psycopg2
    state: latest

- name: Check to ensure the PostgreSQL data directory exists.
  block:
    - stat:
        path: /var/lib/pgsql
      register: pgsql_dir
    - debug:
        msg: "The path {{ pgsql_dir }} is a directory so we need to move it."
      when: pgsql_dir.stat.isdir is defined and pgsql_dir.stat.isdir
    - debug:
        msg: "The path {{ pgsql_dir }} is a symlink already."
      when: pgsql_dir.stat.islnk is defined and pgsql_dir.stat.islnk

- name: Move the PostgreSQL data directory to /data/pgsql and create a symlink
  block:
    - command: mv /var/lib/pgsql /data/pgsql
    - file:
        src: /data/pgsql
        dest: /var/lib/pgsql
        state: link
  when: pgsql_dir.stat.isdir is defined and pgsql_dir.stat.isdir

- name: Initialise the PostgreSQL server
  command: /usr/bin/postgresql-setup --initdb creates=/data/pgsql/data/postgresql.conf
  args:
    creates: /data/pgsql/initdb_postgresql.log
  tags: postgres_initdb

- name: Enable the PostgreSQL server on boot
  systemd:
    name: postgresql
    enabled: yes

- name: Set the PostgreSQL server to listen on all interfaces.
  lineinfile:
    path: /data/pgsql/data/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
    backrefs: yes
  
- name: Set the PostgreSQL auth to md5 for VPC connections.
  lineinfile:
    path: /data/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+ident'
    line: 'host all all {{ ansible_local.network.vpc_cidr }} md5'
    backrefs: yes
  tags: postgres_config-files
  when: host_type != "standalone"

- name: Set the PostgreSQL auth to md5 for localhost connections.
  lineinfile:
    path: /data/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+ident'
    line: 'host all all 127.0.0.1/32 md5'
    backrefs: yes
  tags: postgres_config-files
  when: host_type == "standalone"

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Set password for postgres user
  become_user: postgres
  become: yes
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: postgres
    name: postgres
    password: "{{ ansible_local.environment.db_password }}"
  tags: postgres_set-password
