---
# tasks file for datashades.solr

# Java is not pre-installed on AL2 so we need to get it installed for Solr
- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: latest

# Separate steps for download and extracting are required as the install process requires the original zip file.
# Using unarchive to retrieve a remote file doesn't store the archive locally.
- name: Download the Solr 6.x archive
  get_url:
    url: https://datashades-files.s3-ap-southeast-2.amazonaws.com/solr-6.6.6.zip
    dest: /tmp
  when: solr == '6'

- name: Download the Solr 8.x archive
  get_url:
    url: https://downloads.apache.org/lucene/solr/8.11.1/solr-8.11.1.zip
    dest: /tmp
  when: solr == '8'

- name: Extract the Solr 6.x archive
  unarchive:
    src: /tmp/solr-6.6.6.zip
    dest: /tmp
    remote_src: yes
  when: solr == '6'

- name: Extract the Solr 8.x archive
  unarchive:
    src: /tmp/solr-8.11.1.zip
    dest: /tmp
    remote_src: yes
  when: solr == '8'

- name: Execute the Solr 6.x install script
  shell: ./install_solr_service.sh /tmp/solr-6.6.6.zip
  args:
    chdir: /tmp/solr-6.6.6/bin/
    creates: /var/solr
  when: solr == '6'

- name: Execute the Solr 8.x install script
  shell: ./install_solr_service.sh /tmp/solr-8.11.1.zip
  args:
    chdir: /tmp/solr-8.11.1/bin/
    creates: /var/solr
  when: solr == '8'

- name: Check to ensure the Solr directory exists.
  block:
    - stat:
        path: /var/solr
      register: solr_dir
    - debug:
        msg: "The path /var/solr is a directory so we need to move it."
      when: solr_dir.stat.isdir is defined and solr_dir.stat.isdir
    - debug:
        msg: "The path /var/solr is a symlink already."
      when: solr_dir.stat.islnk is defined and solr_dir.stat.islnk

- name: Move the Solr directory to /data/solr
  block:
    - command: mv /var/solr /data/solr
    - file:
        src: /data/solr
        dest: /var/solr
        state: link
  when: solr_dir.stat.isdir is defined and solr_dir.stat.isdir

- name: Set core name fact.
  set_fact:
    solr_core_name: "{{ ansible_local.environment.environment_type }}_ckan"

- name: Restart Solr before attempting to create a core.
  shell: /etc/init.d/solr restart

- name: Create a new Solr core
  shell: /opt/solr/bin/solr create -c {{ solr_core_name }}
  args:
    creates: /data/solr/data/{{ solr_core_name }}/core.properties
  become: yes
  become_user: solr

- name: Remove managed schema file from new core configuration.
  file:
    path: /data/solr/data/{{ solr_core_name }}/conf/managed-schema
    state: absent

- name: Copy CKAN's Sole 6.x schema.xml
  copy:
    src: schema_solr6_ckan-2.9.xml
    dest: /data/solr/data/{{ solr_core_name }}/conf/schema.xml
    owner: solr
    group: solr
  when: solr == '6'

- name: Copy CKAN's Solr 8.x schema.xml
  copy:
    src: schema_solr8_ckan-2.9.xml
    dest: /data/solr/data/{{ solr_core_name }}/conf/schema.xml
    owner: solr
    group: solr
  when: solr == '8'

- name: Replace solrconfig.xml with updated version compatible with CKAN.
  copy:
    src: solrconfig_6.6.xml
    dest: /data/solr/data/{{ solr_core_name }}/conf/solrconfig.xml
    force: yes
    owner: solr
    group: solr
  when: solr == '6'

- name: Copy JTS module to enable spatial search functionality
  copy:
    src: jts-core-1.16.1.jar
    dest: /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.16.1.jar
    mode: 0644
  when: solr == '6'

- name: Copy JTS module to enable spatial search functionality
  copy:
    src: jts-core-1.18.2.jar
    dest: /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.18.2.jar
    mode: 0644
  when: solr == '8'

- name: Enable Solr on boot
  systemd:
    name: solr
    enabled: yes

- name: Restart Solr
  shell: /etc/init.d/solr restart
