---
# tasks file for datashades.drupal

# Include Amazon Linux 1 tasks
- include: drupal_web-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include Amazon Linux 2 tasks
- include: drupal_web-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
