---
# tasks file for datashades.xloader

- name: Clone XLoader source from Git
  git:
    repo: https://github.com/ckan/ckanext-xloader.git
    clone: yes
    dest: /usr/lib/ckan/default/src/ckanext-xloader
    version: master

- name: Install XLoader requirements
  pip:
    requirements: /usr/lib/ckan/default/src/ckanext-xloader/requirements.txt
    virtualenv: /usr/lib/ckan/default

- name: Install XLoader dev requirements
  pip:
    requirements: /usr/lib/ckan/default/src/ckanext-xloader/dev-requirements.txt
    virtualenv: /usr/lib/ckan/default

- name: Execute python setup
  command: /usr/lib/ckan/default/bin/python setup.py develop 
  args:
    creates: /usr/lib/ckan/default/src/ckanext-xloader/ckanext_xloader.egg-info
    chdir: /usr/lib/ckan/default/src/ckanext-xloader

- name: Set ownership of XLoader's files to CKAN user
  file:
    path: /usr/lib/ckan/default
    owner: ckan
    group: ckan
    recurse: yes

- include: xloader-configuration.yml
