---
# Installs a base CKAN virtualenv and sets up a CKAN Worker process via Supervisor.

- name: Install Python Postgres
  yum:
    name: 
      - python27-psycopg2
      - postgresql96
      - postgresql96-devel
    state: latest

- name: Create CKAN directory
  file:
    path: /usr/lib/ckan
    state: directory
    owner: ckan
    group: ckan

- name: Create CKAN configuration directory
  file:
    path: /etc/ckan/default
    state: directory
    owner: ckan
    group: ckan

# To allow the virtual environment to work correctly under Amazon Linux we need to symlink lib to lib64
# after moving it's contents

# To ensure idempotency, first we:
- name: Create virtualenv for CKAN
  command: virtualenv /usr/lib/ckan/default
  args:
    creates: /usr/lib/ckan/default

- name: Determine if lib directory is a symlink
  block:
    - stat:
        path: /usr/lib/ckan/default/lib
      register: ckan_lib_dir
    - debug:
        msg: "The path /usr/lib/ckan/default/lib is a directory so we have work to do."
      when: ckan_lib_dir.stat.isdir is defined and ckan_lib_dir.stat.isdir
    - debug:
        msg: "The path /usr/lib/ckan/default/lib is a symlink already, no work required."
      when: ckan_lib_dir.stat.islnk is defined and ckan_lib_dir.stat.islnk

# Then we:
- name: Move lib content to lib64 and symlink
  block:
    - shell: mv /usr/lib/ckan/default/lib/python2.7/site-packages/* /usr/lib/ckan/default/lib64/python2.7/site-packages/
      args:
        creates: /usr/lib/ckan/default/lib64/python2.7/site-packages/pip
    - file:
        path: /usr/lib/ckan/default/lib
        state: absent
    - file:
        src: /usr/lib/ckan/default/lib64/
        dest: /usr/lib/ckan/default/lib
        state: link
  when: ckan_lib_dir.stat.isdir is defined and ckan_lib_dir.stat.isdir

- name: Install the required setuptools version
  pip:
    name: setuptools
    version: "20.4"
    virtualenv: /usr/lib/ckan/default

- name: Install CKAN into virtualenv
  shell: /usr/lib/ckan/default/bin/pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.7.3#egg=ckan'
  args:
    creates: /usr/lib/ckan/default/src/ckan/requirements.txt
  tags: ckan_install-release

- name: Install CKAN requirements
  pip:
    requirements: /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default
  tags: ckan_requirements

- name: Set ownership of CKAN files to CKAN's user
  file:
    path: /usr/lib/ckan/default
    owner: ckan
    group: ckan
    recurse: yes
  tags: ckan_worker-ownership

# Do configuration tasks
- include: ckan-configuration.yml

- name: Install CKAN worker daemon
  template:
    src: ckan-worker.conf.j2
    dest: /etc/supervisor.d/ckan-worker.conf

- name: Restart Supervisor
  service:
    name: supervisor
    state: restarted
