---
# Setting up Let's Encrypt for non-prod environments.

- name: Set domain for non-PROD environment
  set_fact:
    ssl_domain: "{{ ansible_local.environment.environment_type }}web.{{ ansible_local.dns.hosted_zone }}"
  when: host_type != "standalone"

- name: Set domain fact for standalone
  set_fact:
    ssl_domain: "{{ ansible_local.dns.dns_name }}"
  when: host_type == "standalone"

- name: Install acme.sh
  shell: wget -O -  https://get.acme.sh | sh -s email="{{ email }}"
  args:
    chdir: /root
    creates: /root/.acme.sh/acme.sh

- name: Ensure destination SSL directory exists
  file:
    path: /etc/ssl/certs/{{ ssl_domain }}
    state: directory
    mode: 0755

- name: Stop nginx to ensure certbot can bind to port 80
  service:
    name: nginx
    state: stopped

- name: Generate new certificate for non-PROD environments
  shell: /root/.acme.sh/acme.sh --issue --standalone -d {{ ssl_domain }} --server letsencrypt
  args:
    creates: /root/.acme.sh/{{ ssl_domain }}/fullchain.cer
  when: host_type != "standalone"

- name: Install certificate for non-PROD environment
  shell: /root/.acme.sh/acme.sh --install-cert -d {{ ssl_domain }} --cert-file /etc/ssl/certs/{{ ssl_domain }}/cert.pem --key-file /etc/ssl/certs/{{ ssl_domain }}/private.key --fullchain-file /etc/ssl/certs/{{ ssl_domain }}/fullchain.cer --reloadcmd "service nginx restart"
  args:
    creates: /etc/ssl/certs/{{ ssl_domain }}/fullchain.cer
  when: host_type != "standalone"

- name: Generate new certificate for standalone
  shell: /root/.acme.sh/acme.sh --issue --standalone -d {{ ssl_domain }} --server letsencrypt
  args:
    creates: /root/.acme.sh/{{ ssl_domain }}/fullchain.cer
  when: host_type == "standalone"

- name: Install certificate for standalone
  shell: /root/.acme.sh/acme.sh --install-cert -d {{ ssl_domain }} --cert-file /etc/ssl/certs/{{ ssl_domain }}/cert.pem --key-file /etc/ssl/certs/{{ ssl_domain }}/private.key --fullchain-file /etc/ssl/certs/{{ ssl_domain }}/fullchain.cer --reloadcmd "service nginx restart"
  args:
    creates: /etc/ssl/certs/{{ ssl_domain }}/fullchain.cer
  when: host_type == "standalone"

- name: Add pre hook to Acme configuration
  ini_file:
    path: /root/.acme.sh/{{ ssl_domain }}/{{ ssl_domain }}.conf
    section:
    option: Le_PreHook
    value: "'systemctl stop nginx'"
    no_extra_spaces: yes

- name: Add post hook to Acme configuration
  ini_file:
    path: /root/.acme.sh/{{ ssl_domain }}/{{ ssl_domain }}.conf
    section:
    option: Le_PostHook
    value: "'systemctl start nginx'"
    no_extra_spaces: yes
