---
# tasks file for datashades.nginx

# Include Amazon Linux 1 tasks
- include: nginx-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include Amazon Linux 2 tasks
- include: nginx-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
