---
# tasks file for datashades.webmaster-admin-scripts

# Include Amazon Linxu 1 tasks
- include: webmaster_admin-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include Amazon Linux 2 tasks
- include: webmaster_admin-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
