---
# tasks file for datashades.webmaster-admin-scripts

- name: Copy chkdns script
  copy:
    src: chkdns
    dest: /sbin/chkdns
    mode: 0755
  when: ansible_local.environment.environment_type != "prod" or host_type == "standalone"
  tags:
    - webmaster-admin_chkdns

- name: Add chkdns script to rc.local
  lineinfile:
    path: /etc/rc.local
    line: "/sbin/chkdns"
    state: present
  when: ansible_local.environment.environment_type != "prod" or host_type == "standalone"
  tags:
    - webmaster-admin_updatedns-chkdns

- name: Add execute permissions to rc.local
  file:
    path: /etc/rc.d/rc.local
    mode: 0755

- name: Execute chkdns script
  shell: /sbin/chkdns
  when: ansible_local.environment.environment_type != "prod" or host_type == "standalone"

- name: For non-prod environment, pause for a short time to help prevent Let's Encrypt verify failure later.
  pause:
    seconds: 30
  when: ansible_local.environment.environment_type != "prod"

- name: Copy updateasg script
  copy: 
    src: updateasg
    dest: /sbin/updateasg
    mode: 0755
  when: host_type != "standalone"

- name: Create CKAN group
  group:
    name: ckan
    state: present
    gid: 1500

- name: Create CKAN user
  user:
    name: ckan
    shell: /sbin/nologin
    uid: 1500
    non_unique: yes
    groups: 
      - ckan
   
- name: Create NFS directories
  file:
    path: /var/shared_content
    state: directory
    owner: ckan
    group: ckan
    mode: 0775
  when: host_type != "standalone"

- name: Symlink shared content for standalone instance.
  file:
    src: /data/nfs/shared_content
    dest: /var/shared_content
    state: link
    owner: ckan
    group: ckan
  when: host_type == "standalone"

- name: Mount EFS
  block:
    - mount:
        path: /var/shared_content
        src: "{{ ansible_local.environment.efs_id }}.efs.{{ ansible_local.environment.aws_region }}.amazonaws.com:/shared_content"
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
        state: mounted
  when: ansible_local.environment.efs_id != "NA"

- name: Mount NFS
  block:
    - mount:
        path: /var/shared_content
        src: "{{ ansible_local.environment.environment_type }}nfs.{{ ansible_local.dns.hosted_zone }}:/data/nfs/shared_content"
        fstype: nfs
        opts: rw,hard,intr
        state: mounted
  when: ansible_local.environment.efs_id == "NA" and host_type != "standalone"

- name: Copy backup script for DEV/UAT (no scaling group, no AMI)
  copy:
    src: backup-scripts/ebs_backup_daily
    dest: /root/ebs_backup_daily
    mode: 0755
  when: ansible_local.environment.environment_type != "prod"

- name: Enable backup cron for DEV/UAT
  cron:
    name: "Daily backup"
    cron_file: /etc/crontab
    user: root
    job: "/root/ebs_backup_daily >> /var/log/ebs_daily.log 2>&1"
    minute: 0
    hour: 9
  when: ansible_local.environment.environment_type != "prod"
