---
# tasks file for datashades.common

# Fix for constant yum lock errors whenever yum is called via Ansible on AL2
- name: Disable update-motd yum plugin
  ini_file:
    path: /etc/yum/pluginconf.d/update-motd.conf
    section: main
    option: enabled
    value: "0"
    no_extra_spaces: yes

- name: Update OS packages
  yum:
    name: '*'
    state: latest
  tags:
    - common_yum-update

- name: Set the server timezone
  timezone:
    name: "{{ datashades_common_timezone }}"
  notify:
    - restart crond
    - restart chronyd
  tags:
    - common_timezone

- name: Enable EPEL Yum repository (Amazon Linux 2)
  shell: amazon-linux-extras install epel -y
  args:
    creates: /etc/yum.repos.d/epel.repo
  environment:
    PYTHON: "python2"

- name: Install packages required for use later (xfsprogs, yum-cron, expect)
  yum:
    name:
      - xfsprogs
      - yum-cron
      - expect
      - git
      - gcc
      - python-virtualenv
      - python-boto
      - python-pip
      - pcre-devel
      - patch
      - bzip2-devel
    state: latest
  tags:
    - common_yum-install

- name: Enable yum-cron on boot
  service:
    name: yum-cron
    enabled: yes
  notify:
    - restart yum-cron
  tags:
    - common_yum-cron-enable

- name: Enable Nano syntax highlighting
  copy:
    src: nanorc
    dest: /etc/nanorc
    force: yes
    backup: yes
  tags:
    - common_nano-config

- name: Add custom Bash profile for Datashades
  copy:
    src: datashades-bash-profile
    dest: /etc/profile.d/datashades.sh
  tags:
    - common_bash-profile

- name: Create swap file
  command: 'dd if=/dev/zero of=/var/swapFile bs=1G count=2'
  args:
    creates: /var/swapFile

- name: Change swap file permissions
  file:
    path: /var/swapFile
    owner: root
    group: root
    mode: 0600

- name: "Check swap file type"
  command: file /var/swapFile
  register: swapfile

- name: Make swap file
  command: "mkswap /var/swapFile"
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount:
    name: none
    src: /var/swapFile
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present

- name: Mount swap
  command: "swapon /var/swapFile"
  when: ansible_swaptotal_mb < 1

- name: Increase max socket connections via sysctl
  copy:
    src: sysctl-uwsgi.conf
    dest: /etc/sysctl.d/50-uwsgi.conf

- name: Reload sysctl values
  shell: sysctl --system
