---
# tasks file for datashades.common

- name: Update OS packages
  yum:
    name: '*'
    state: latest
  tags:
    - common_yum-update

- name: Set the server timezone
  timezone:
    name: "{{ datashades_common_timezone }}"
  notify:
    - restart crond
    - restart ntpd
  tags:
    - common_timezone

- name: Enable EPEL Yum repositoy
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 1
  tags:
    - common_epel-enable

- name: Install packages required for use later (xfsprogs, yum-cron, expect)
  yum:
    name: 
      - xfsprogs
      - yum-cron
      - expect
      - git
      - gcc
    state: latest
  tags:
    - common_yum-install

- name: Enable yum-cron on boot
  service:
    name: yum-cron
    enabled: yes
  notify:
    - restart yum-cron
  tags:
    - common_yum-cron-enable

- name: Enable Nano syntax highlighting
  copy:
    src: nanorc
    dest: /etc/nanorc
    force: yes
    backup: yes
  tags:
    - common_nano-config

- name: Add custom Bash profile for Datashades
  copy:
    src: datashades-bash-profile
    dest: /etc/profile.d/datashades.sh
  tags:
    - common_bash-profile

- name: Remove amzn Python Install Layout sh (Amazon Linux 1)
  copy:
    src: python-install-layout_sh
    dest: /etc/profile.d/python-install-layout.sh
    force: yes
  tags:
    - common_python-layout

- name: Remove amzn Python Install Layout csh (Amazon Linux 1)
  copy:
    src: python-install-layout_csh
    dest: /etc/profile.d/python-install-layout.csh
    force: yes
  tags:
    - common_python-layout
