---
# tasks file for datashades.mysql

# Include Amazon Linux 1 tasks
- include: mysql-al1.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

# Include Amazon Linux 2 tasks
- include: mysql-al2.yml
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
