---
# tasks file for datashades.mysql

- name: Install MySQL
  yum:
    name: 
      - mariadb-server
      - mariadb
      - MySQL-python
    state: latest

- name: Enable MySQL on boot
  systemd:
    name: mariadb
    enabled: yes

- name: Start MySQL
  systemd:
    name: mariadb
    state: restarted

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ansible_local.environment.db_password }}"
    host: "localhost"
    login_user: root
    login_password: ""
  tags: mysql_root-user

- name: Create ~/.my.cnf containing root credentials
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
